# Generated by Django 3.1.2 on 2020-12-11 22:52

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_temas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage('C:\\Users\\trilo\\Django\\quiz\\static'), upload_to='./preguntas_respuestas/'),
        ),
        migrations.CreateModel(
            name='TemasPreguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preguntas.pregunta')),
                ('idtema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preguntas.temas')),
            ],
        ),
    ]
